#include "tetromino.h"
#include <GL/glew.h>
#ifdef __APPLE__
# define __gl_h_
# define GL_DO_NOT_WARN_IF_MULTI_GL_VERSION_HEADERS_INCLUDED
#endif
#include <OpenGL/gl3.h>
#define __gl_h_
#include <GL/freeglut.h>
#include <GL/glut.h>


void dibuja_cuadrado(PIEZA *pieza, int dif_x, int dif_y)
{
  glColor3f(1.0f,0.0f,1.0f);
  if(pieza->activo_centro)
    glRectf(pieza->x-(dif_x),
	    pieza->y-(dif_y),
	    pieza->x-(dif_x)+1,
	    pieza->y-(dif_y)+1);
  if(pieza->bloques[0]->activo)
    glRectf(pieza->bloques[0]->x-(dif_x),
	    pieza->bloques[0]->y-(dif_y),
	    pieza->bloques[0]->x-(dif_x)+1,
	    pieza->bloques[0]->y-(dif_y)+1);
  if(pieza->bloques[1]->activo)
    glRectf(pieza->bloques[1]->x-(dif_x),
	    pieza->bloques[1]->y-(dif_y),
	    pieza->bloques[1]->x-(dif_x)+1,
	    pieza->bloques[1]->y-(dif_y)+1);
  if(pieza->bloques[2]->activo)
    glRectf(pieza->bloques[2]->x-(dif_x),
	    pieza->bloques[2]->y-(dif_y),
	    pieza->bloques[2]->x-(dif_x)+1,
	    pieza->bloques[2]->y-(dif_y)+1);
  glColor3f(1.0f,1.0f,1.0f);
}

void dibuja_left_gun(PIEZA *pieza, int dif_x, int dif_y)
{
  glColor3f(0.5f,0.0f,0.5f);
  if(pieza->activo_centro)
    glRectf(pieza->x-(dif_x),
	    pieza->y-(dif_y),
	    pieza->x-(dif_x)+1,
	    pieza->y-(dif_y)+1);
  if(pieza->orientacion == 0){
    if(pieza->bloques[0]->activo)
      glRectf(pieza->bloques[0]->x-(dif_x),
	      pieza->bloques[0]->y-(dif_y),
	      pieza->bloques[0]->x-(dif_x)+1,
	      pieza->bloques[0]->y-(dif_y)+1);
    if(pieza->bloques[1]->activo)
      glRectf(pieza->bloques[1]->x-(dif_x),
	      pieza->bloques[1]->y-(dif_y),
	      pieza->bloques[1]->x-(dif_x)+1,
	      pieza->bloques[1]->y-(dif_y)+1);
    if(pieza->bloques[2]->activo)
      glRectf(pieza->bloques[2]->x-(dif_x),
	      pieza->bloques[2]->y-(dif_y),
	      pieza->bloques[2]->x-(dif_x)+1,
	      pieza->bloques[2]->y-(dif_y)+1);
  }else if(pieza->orientacion == 90){
    if(pieza->bloques[0]->activo)
      glRectf(pieza->bloques[0]->x-(dif_x),
	      pieza->bloques[0]->y-(dif_y),
	      pieza->bloques[0]->x-(dif_x)+1,
	      pieza->bloques[0]->y-(dif_y)+1);
    if(pieza->bloques[1]->activo)
      glRectf(pieza->bloques[1]->x-(dif_x),
	      pieza->bloques[1]->y-(dif_y),
	      pieza->bloques[1]->x-(dif_x)+1,
	      pieza->bloques[1]->y-(dif_y)+1);
    if(pieza->bloques[2]->activo)
      glRectf(pieza->bloques[2]->x-(dif_x),
	      pieza->bloques[2]->y-(dif_y),
	      pieza->bloques[2]->x-(dif_x)+1,
	      pieza->bloques[2]->y-(dif_y)+1);
  }else if(pieza->orientacion == 180){
    if(pieza->bloques[0]->activo)
      glRectf(pieza->bloques[0]->x-(dif_x),
	      pieza->bloques[0]->y-(dif_y),
	      pieza->bloques[0]->x-(dif_x)+1,
	      pieza->bloques[0]->y-(dif_y)+1);
    if(pieza->bloques[1]->activo)
      glRectf(pieza->bloques[1]->x-(dif_x),
	      pieza->bloques[1]->y-(dif_y),
	      pieza->bloques[1]->x-(dif_x)+1,
	      pieza->bloques[1]->y-(dif_y)+1);
    if(pieza->bloques[2]->activo)
      glRectf(pieza->bloques[2]->x-(dif_x),
	      pieza->bloques[2]->y-(dif_y),
	      pieza->bloques[2]->x-(dif_x)+1,
	      pieza->bloques[2]->y-(dif_y)+1);
  }else{
    if(pieza->bloques[0]->activo)
      glRectf(pieza->bloques[0]->x-(dif_x),
	      pieza->bloques[0]->y-(dif_y),
	      pieza->bloques[0]->x-(dif_x)+1,
	      pieza->bloques[0]->y-(dif_y)+1);
    if(pieza->bloques[1]->activo)
      glRectf(pieza->bloques[1]->x-(dif_x),
	      pieza->bloques[1]->y-(dif_y),
	      pieza->bloques[1]->x-(dif_x)+1,
	      pieza->bloques[1]->y-(dif_y)+1);
    if(pieza->bloques[2]->activo)
      glRectf(pieza->bloques[2]->x-(dif_x),
	      pieza->bloques[2]->y-(dif_y),
	      pieza->bloques[2]->x-(dif_x)+1,
	      pieza->bloques[2]->y-(dif_y)+1);
  }
  glColor3f(1.0f,1.0f,1.0f);
}

void dibuja_right_gun(PIEZA *pieza, int dif_x, int dif_y)
{
  glColor3f(0.0f,0.5f,0.5f);
  if(pieza->activo_centro)
    glRectf(pieza->x-(dif_x),
	    pieza->y-(dif_y),
	    pieza->x-(dif_x)+1,
	    pieza->y-(dif_y)+1);
  if(pieza->orientacion == 0){
    if(pieza->bloques[0]->activo)
      glRectf(pieza->bloques[0]->x-(dif_x),
	      pieza->bloques[0]->y-(dif_y),
	      pieza->bloques[0]->x-(dif_x)+1,
	      pieza->bloques[0]->y-(dif_y)+1);
    if(pieza->bloques[1]->activo)
      glRectf(pieza->bloques[1]->x-(dif_x),
	      pieza->bloques[1]->y-(dif_y),
	      pieza->bloques[1]->x-(dif_x)+1,
	      pieza->bloques[1]->y-(dif_y)+1);
    if(pieza->bloques[2]->activo)
      glRectf(pieza->bloques[2]->x-(dif_x),
	      pieza->bloques[2]->y-(dif_y),
	      pieza->bloques[2]->x-(dif_x)+1,
	      pieza->bloques[2]->y-(dif_y)+1);
  }else if(pieza->orientacion == 90){
    if(pieza->bloques[0]->activo)
      glRectf(pieza->bloques[0]->x-(dif_x),
	      pieza->bloques[0]->y-(dif_y),
	      pieza->bloques[0]->x-(dif_x)+1,
	      pieza->bloques[0]->y-(dif_y)+1);
    if(pieza->bloques[1]->activo)
      glRectf(pieza->bloques[1]->x-(dif_x),
	      pieza->bloques[1]->y-(dif_y),
	      pieza->bloques[1]->x-(dif_x)+1,
	      pieza->bloques[1]->y-(dif_y)+1);
    if(pieza->bloques[2]->activo)
      glRectf(pieza->bloques[2]->x-(dif_x),
	      pieza->bloques[2]->y-(dif_y),
	      pieza->bloques[2]->x-(dif_x)+1,
	      pieza->bloques[2]->y-(dif_y)+1);
  }else if(pieza->orientacion == 180){
    if(pieza->bloques[0]->activo)
      glRectf(pieza->bloques[0]->x-(dif_x),
	      pieza->bloques[0]->y-(dif_y),
	      pieza->bloques[0]->x-(dif_x)+1,
	      pieza->bloques[0]->y-(dif_y)+1);
    if(pieza->bloques[1]->activo)
      glRectf(pieza->bloques[1]->x-(dif_x),
	      pieza->bloques[1]->y-(dif_y),
	      pieza->bloques[1]->x-(dif_x)+1,
	      pieza->bloques[1]->y-(dif_y)+1);
    if(pieza->bloques[2]->activo)
      glRectf(pieza->bloques[2]->x-(dif_x),
	      pieza->bloques[2]->y-(dif_y),
	      pieza->bloques[2]->x-(dif_x)+1,
	      pieza->bloques[2]->y-(dif_y)+1);
  }else{
    if(pieza->bloques[0]->activo)
      glRectf(pieza->bloques[0]->x-(dif_x),
	      pieza->bloques[0]->y-(dif_y),
	      pieza->bloques[0]->x-(dif_x)+1,
	      pieza->bloques[0]->y-(dif_y)+1);
    if(pieza->bloques[1]->activo)
      glRectf(pieza->bloques[1]->x-(dif_x),
	      pieza->bloques[1]->y-(dif_y),
	      pieza->bloques[1]->x-(dif_x)+1,
	      pieza->bloques[1]->y-(dif_y)+1);
    if(pieza->bloques[2]->activo)
      glRectf(pieza->bloques[2]->x-(dif_x),
	      pieza->bloques[2]->y-(dif_y),
	      pieza->bloques[2]->x-(dif_x)+1,
	      pieza->bloques[2]->y-(dif_y)+1);
  }
  glColor3f(1.0f,1.0f,1.0f);
}

void dibuja_left_snake(PIEZA *pieza, int dif_x, int dif_y)
{
  glColor3f(0.6f,0.4f,0.3f);
  if(pieza->activo_centro)
    glRectf(pieza->x-(dif_x)
	    ,pieza->y-(dif_y)
	    ,pieza->x-(dif_x)+1
	    ,pieza->y-(dif_y)+1);  
  if(pieza->orientacion == 0 || pieza->orientacion == 180){
    if(pieza->bloques[0]->activo)
      glRectf(pieza->bloques[0]->x-(dif_x),
	      pieza->bloques[0]->y-(dif_y),
	      pieza->bloques[0]->x-(dif_x)+1,
	      pieza->bloques[0]->y-(dif_y)+1);
    if(pieza->bloques[1]->activo)
      glRectf(pieza->bloques[1]->x-(dif_x),
	      pieza->bloques[1]->y-(dif_y),
	      pieza->bloques[1]->x-(dif_x)+1,
	      pieza->bloques[1]->y-(dif_y)+1);
    if(pieza->bloques[2]->activo)
      glRectf(pieza->bloques[2]->x-(dif_x),
	      pieza->bloques[2]->y-(dif_y),
	      pieza->bloques[2]->x-(dif_x)+1,
	      pieza->bloques[2]->y-(dif_y)+1);
  }else{
    if(pieza->bloques[0]->activo)
      glRectf(pieza->bloques[0]->x-(dif_x),
	      pieza->bloques[0]->y-(dif_y),
	      pieza->bloques[0]->x-(dif_x)+1,
	      pieza->bloques[0]->y-(dif_y)+1);
    if(pieza->bloques[1]->activo)
      glRectf(pieza->bloques[1]->x-(dif_x),
	      pieza->bloques[1]->y-(dif_y),
	      pieza->bloques[1]->x-(dif_x)+1,
	      pieza->bloques[1]->y-(dif_y)+1);
    if(pieza->bloques[2]->activo)
      glRectf(pieza->bloques[2]->x-(dif_x),
	      pieza->bloques[2]->y-(dif_y),
	      pieza->bloques[2]->x-(dif_x)+1,
	      pieza->bloques[2]->y-(dif_y)+1);
  }
  glColor3f(1.0f,1.0f,1.0f);
}

void dibuja_right_snake(PIEZA *pieza, int dif_x, int dif_y)
{
  glColor3f(0.0f,0.9f,0.0f);
  if(pieza->activo_centro)
    glRectf(pieza->x-(dif_x),
	    pieza->y-(dif_y),
	    pieza->x-(dif_x)+1,
	    pieza->y-(dif_y)+1);
  if(pieza->orientacion == 0 || pieza->orientacion == 180){
    if(pieza->bloques[0]->activo)
      glRectf(pieza->bloques[0]->x-(dif_x),
	      pieza->bloques[0]->y-(dif_y),
	      pieza->bloques[0]->x-(dif_x)+1,
	      pieza->bloques[0]->y-(dif_y)+1);
    if(pieza->bloques[1]->activo)
      glRectf(pieza->bloques[1]->x-(dif_x),
	      pieza->bloques[1]->y-(dif_y),
	      pieza->bloques[1]->x-(dif_x)+1,
	      pieza->bloques[1]->y-(dif_y)+1);
    if(pieza->bloques[2]->activo)
      glRectf(pieza->bloques[2]->x-(dif_x),
	      pieza->bloques[2]->y-(dif_y),
	      pieza->bloques[2]->x-(dif_x)+1,
	      pieza->bloques[2]->y-(dif_y)+1);
  }else{
    if(pieza->bloques[0]->activo)
      glRectf(pieza->bloques[0]->x-(dif_x),
	      pieza->bloques[0]->y-(dif_y),
	      pieza->bloques[0]->x-(dif_x)+1,
	      pieza->bloques[0]->y-(dif_y)+1);
    if(pieza->bloques[1]->activo)
      glRectf(pieza->bloques[1]->x-(dif_x),
	      pieza->bloques[1]->y-(dif_y),
	      pieza->bloques[1]->x-(dif_x)+1,
	      pieza->bloques[1]->y-(dif_y)+1);
    if(pieza->bloques[2]->activo)
      glRectf(pieza->bloques[2]->x-(dif_x),
	      pieza->bloques[2]->y-(dif_y),
	      pieza->bloques[2]->x-(dif_x)+1,
	      pieza->bloques[2]->y-(dif_y)+1);
  }
  glColor3f(1.0f,1.0f,1.0f);
}

void dibuja_i(PIEZA *pieza, int dif_x, int dif_y)
{
  glColor3f(0.0f,0.0f,1.0f);
  if(pieza->activo_centro)
    glRectf(pieza->x-(dif_x),
	    pieza->y-(dif_y),
	    pieza->x-(dif_x)+1,
	    pieza->y-(dif_y)+1);
  if(pieza->orientacion == 0 || pieza->orientacion == 180){
    if(pieza->bloques[0]->activo)
      glRectf(pieza->bloques[0]->x-(dif_x),
	      pieza->bloques[0]->y-(dif_y),
	      pieza->bloques[0]->x-(dif_x)+1,
	      pieza->bloques[0]->y-(dif_y)+1);
    if(pieza->bloques[1]->activo)
      glRectf(pieza->bloques[1]->x-(dif_x),
	      pieza->bloques[1]->y-(dif_y),
	      pieza->bloques[1]->x-(dif_x)+1,
	      pieza->bloques[1]->y-(dif_y)+1);
    if(pieza->bloques[2]->activo)
      glRectf(pieza->bloques[2]->x-(dif_x),
	      pieza->bloques[2]->y-(dif_y),
	      pieza->bloques[2]->x-(dif_x)+1,
	      pieza->bloques[2]->y-(dif_y)+1);
  }else{
    if(pieza->bloques[0]->activo)
      glRectf(pieza->bloques[0]->x-(dif_x),
	      pieza->bloques[0]->y-(dif_y),
	      pieza->bloques[0]->x-(dif_x)+1,
	      pieza->bloques[0]->y-(dif_y)+1);
    if(pieza->bloques[1]->activo)
      glRectf(pieza->bloques[1]->x-(dif_x),
	      pieza->bloques[1]->y-(dif_y),
	      pieza->bloques[1]->x-(dif_x)+1,
	      pieza->bloques[1]->y-(dif_y)+1);
    if(pieza->bloques[2]->activo)
      glRectf(pieza->bloques[2]->x-(dif_x),
	      pieza->bloques[2]->y-(dif_y),
	      pieza->bloques[2]->x-(dif_x)+1,
	      pieza->bloques[2]->y-(dif_y)+1);
  }
  glColor3f(1.0f,1.0f,1.0f);
}

void dibuja_t(PIEZA *pieza, int dif_x, int dif_y)
{
  glColor3f(1.0f,0.0f,0.0f);
  if(pieza->activo_centro)
    glRectf(pieza->x-(dif_x),
	    pieza->y-(dif_y),
	    pieza->x-(dif_x)+1,
	    pieza->y-(dif_y)+1);
  if(pieza->orientacion == 0){
    if(pieza->bloques[0]->activo)
      glRectf(pieza->bloques[0]->x-(dif_x),
	      pieza->bloques[0]->y-(dif_y),
	      pieza->bloques[0]->x-(dif_x)+1,
	      pieza->bloques[0]->y-(dif_y)+1);
    if(pieza->bloques[1]->activo)
      glRectf(pieza->bloques[1]->x-(dif_x),
	      pieza->bloques[1]->y-(dif_y),
	      pieza->bloques[1]->x-(dif_x)+1,
	      pieza->bloques[1]->y-(dif_y)+1);
    if(pieza->bloques[2]->activo)
      glRectf(pieza->bloques[2]->x-(dif_x),
	      pieza->bloques[2]->y-(dif_y),
	      pieza->bloques[2]->x-(dif_x)+1,
	      pieza->bloques[2]->y-(dif_y)+1);
  }else if(pieza->orientacion == 90){
    if(pieza->bloques[0]->activo)
      glRectf(pieza->bloques[0]->x-(dif_x),
	      pieza->bloques[0]->y-(dif_y),
	      pieza->bloques[0]->x-(dif_x)+1,
	      pieza->bloques[0]->y-(dif_y)+1);
    if(pieza->bloques[1]->activo)
      glRectf(pieza->bloques[1]->x-(dif_x),
	      pieza->bloques[1]->y-(dif_y),
	      pieza->bloques[1]->x-(dif_x)+1,
	      pieza->bloques[1]->y-(dif_y)+1);
    if(pieza->bloques[2]->activo)
      glRectf(pieza->bloques[2]->x-(dif_x),
	      pieza->bloques[2]->y-(dif_y),
	      pieza->bloques[2]->x-(dif_x)+1,
	      pieza->bloques[2]->y-(dif_y)+1);
  }else if(pieza->orientacion == 180){
    if(pieza->bloques[0]->activo)
      glRectf(pieza->bloques[0]->x-(dif_x),
	      pieza->bloques[0]->y-(dif_y),
	      pieza->bloques[0]->x-(dif_x)+1,
	      pieza->bloques[0]->y-(dif_y)+1);
    if(pieza->bloques[1]->activo)
      glRectf(pieza->bloques[1]->x-(dif_x),
	      pieza->bloques[1]->y-(dif_y),
	      pieza->bloques[1]->x-(dif_x)+1,
	      pieza->bloques[1]->y-(dif_y)+1);
    if(pieza->bloques[2]->activo)
      glRectf(pieza->bloques[2]->x-(dif_x),
	      pieza->bloques[2]->y-(dif_y),
	      pieza->bloques[2]->x-(dif_x)+1,
	      pieza->bloques[2]->y-(dif_y)+1);
  }else{
    if(pieza->bloques[0]->activo)
      glRectf(pieza->bloques[0]->x-(dif_x),
	      pieza->bloques[0]->y-(dif_y),
	      pieza->bloques[0]->x-(dif_x)+1,
	      pieza->bloques[0]->y-(dif_y)+1);
    if(pieza->bloques[1]->activo)
      glRectf(pieza->bloques[1]->x-(dif_x),
	      pieza->bloques[1]->y-(dif_y),
	      pieza->bloques[1]->x-(dif_x)+1,
	      pieza->bloques[1]->y-(dif_y)+1);
    if(pieza->bloques[2]->activo)
      glRectf(pieza->bloques[2]->x-(dif_x),
	      pieza->bloques[2]->y-(dif_y),
	      pieza->bloques[2]->x-(dif_x)+1,
	      pieza->bloques[2]->y-(dif_y)+1);
  }
  glColor3f(1.0f,1.0f,1.0f);
}
